[package]
name = "webtutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "*"
strum = "0.20"
strum_macros = "0.20"
serde = "1"
serde_derive = "1"
